[package]
name = "sql_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
colored = "3.0.0"
logos = "0.15.1"
nom = "8.0.0"
pratt = "0.4.0"
recursive = "0.1.1"
strsim = "0.11.1"
thiserror = "2.0.16"
